name: park_uptime
version: "1.0.0"
config-version: 2

profile: park_uptime

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  park_uptime:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

vars:
  park_open_hour: 9
  park_close_hour: 22
  snapshot_interval_minutes: 15
  min_downtime_minutes: 15
